spring.application.name=fitnesstracker

spring.datasource.url=jdbc:mariadb://localhost:3306/fitnessdb
spring.datasource.username=fitnessapp
spring.datasource.password=fitnessappuserpas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

